# Generated by Django 2.1.2 on 2018-11-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_pessoa', models.CharField(max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('nome_cliente', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contato_preferencial', models.CharField(max_length=1)),
                ('telefone_contato', models.EmailField(max_length=11)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Cliente')),
            ],
            options={
                'db_table': 'contato',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_faturamento', models.CharField(max_length=1)),
                ('end_entrega', models.CharField(max_length=1)),
                ('end_preferencial', models.CharField(max_length=1)),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Cliente')),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
