# Generated by Django 2.1.2 on 2018-11-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0002_auto_20181126_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_categoria', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_especie', models.CharField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Categoria')),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_tipo', models.CharField(max_length=20)),
                ('cd_produto', models.CharField(max_length=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Categoria')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Especie')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
