# Generated by Django 2.1.2 on 2018-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0004_auto_20181126_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
