# Generated by Django 2.1.2 on 2018-11-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0006_auto_20181126_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('vl_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cd_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Produto')),
            ],
            options={
                'db_table': 'itenspedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(verbose_name='data pedido')),
                ('local_entrega', models.CharField(max_length=100)),
                ('local_faturamento', models.CharField(max_length=100)),
                ('data_entrega', models.DateTimeField(verbose_name='data entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Pedido'),
        ),
    ]
