# Generated by Django 2.1.2 on 2018-11-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0007_auto_20181127_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
    ]
