# Generated by Django 2.1.2 on 2018-11-28 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0008_auto_20181128_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='end_preferencial',
            new_name='fl_preferencial',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='end_entrega',
            new_name='tp_endereco',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_faturamento',
        ),
        migrations.AddField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(default=datetime.datetime(2018, 11, 28, 18, 14, 9, 756156, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=datetime.datetime(2018, 11, 28, 18, 14, 40, 748694, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Cliente'),
            preserve_default=False,
        ),
    ]
