# Generated by Django 2.1.2 on 2018-12-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0009_auto_20181128_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='estado',
            new_name='uf',
        ),
    ]
