# Generated by Django 2.1.2 on 2018-12-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tstpedido', '0010_auto_20181203_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Produto')),
            ],
            options={
                'db_table': 'preco',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_unidade', models.CharField(max_length=20, unique=True)),
                ('abreviatura', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'unidade',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tstpedido.Unidade'),
        ),
    ]
